name: Deploy app

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: stp-ch
  GCP_REGION: europe-west6
  SERVICE_NAME: localsearch-assessment

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    outputs:
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: development
          initial-status: in_progress

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build app # To generate next-env.d.ts for typechecking
        run: npm run build

      - name: Check types
        run: npm run typecheck

      - name: Lint JavaScript
        run: npm run lint

      - name: Lint CSS
        run: npm run stylelint

      - name: Run tests
        run: npm test

      - if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: failure
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          create_credentials_file: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/github/${{ env.SERVICE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secret-files: |
            gcp_credentials=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}

      - if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: failure
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to Google Cloud
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/github/${{ env.SERVICE_NAME }}:latest \
          --region ${{ env.GCP_REGION }} \
          --memory 1Gi \
          --cpu 1 \
          --concurrency 20 \
          --min-instances 0 \
          --max-instances 1 \
          --port 3000 \
          --allow-unauthenticated \
          --network default \
          --vpc-egress private-ranges-only \
          --quiet

      - uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          deployment-id: ${{ needs.test.outputs.deployment_id }}

      - if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: failure
          deployment-id: ${{ needs.test.outputs.deployment_id }}
